##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_header_comments
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_generate_comment_headers
funding:
  - https://www.buymeacoffee.com/dev_cetera
description: A tool to generate header comments for your source files.
version: 0.5.1
topics:
  - source-gen
  - build-runner
  - code-generation
  - comments
  - header-comments

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  path: ^1.9.1
  args: ^2.7.0

  df_config: ^0.7.5
  df_gen_core: ^0.7.0
  df_log: ^0.3.19

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^6.0.0

## -----------------------------------------------------------------------------

executables:
  --headers: df_generate_header_comments
  df_generate_header_comments: df_generate_header_comments

