##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_header_comments
description: A tool to generate header comments for your source files.
version: 0.4.3
repository: https://github.com/dev-cetera/df_generate_header_comments
funding:
  - https://www.buymeacoffee.com/dev_cetera
topics:
  - source-gen
  - build-runner
  - code-generation
  - comments
  - header-comments

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_config: ^0.7.2
  df_gen_core: ^0.6.10
  df_log: ^0.3.11
  path: ^1.9.1
  args: ^2.7.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^6.0.0

## -----------------------------------------------------------------------------

executables:
  gen-header-comments: gen_header_comments
  gen-header-comments-df: gen_header_comments_df
